export const ITEMS = [
  { id: "1", name: "Blue T-shirt" },
  { id: "2", name: "Red Sneakers" },
  { id: "3", name: "Wireless Mouse" },
  { id: "4", name: "Gaming Keyboard" },
  { id: "5", name: "Noise Cancelling Headphones" },
  { id: "6", name: "Laptop Stand" },
  { id: "7", name: "Portable Charger" },
  { id: "8", name: "USB-C Hub" },
  { id: "9", name: "Bluetooth Speaker" },
  { id: "10", name: "Smartphone Holder" },
  { id: "11", name: "Fitness Tracker" },
  { id: "12", name: "Wireless Earbuds" },
  { id: "13", name: "4K Monitor" },
  { id: "14", name: "Webcam" },
  { id: "15", name: "LED Desk Lamp" },
  { id: "16", name: "Ergonomic Chair" },
  { id: "17", name: "Desk Organizer" },
  { id: "18", name: "Wireless Charger" },
  { id: "19", name: "Graphic Tablet" },
  { id: "20", name: "VR Headset" },
  { id: "21", name: "External Hard Drive" },
  { id: "22", name: "Mechanical Keyboard" },
  { id: "23", name: "Gaming Mouse" },
  { id: "24", name: "Smart Thermostat" },
  { id: "25", name: "Robot Vacuum" },
  { id: "26", name: "Air Purifier" },
  { id: "27", name: "Smart Doorbell" },
  { id: "28", name: "Home Security Camera" },
  { id: "29", name: "Electric Toothbrush" },
  { id: "30", name: "Smart Light Bulb" },
  { id: "31", name: "Fitness Equipment" },
  { id: "32", name: "Smart Watch" },
  { id: "33", name: "Digital Picture Frame" },
  { id: "34", name: "Coffee Maker" },
  { id: "35", name: "Blender" },
  { id: "36", name: "Instant Pot" },
  { id: "37", name: "Air Fryer" },
  { id: "38", name: "Sous Vide" },
  { id: "39", name: "Smart Scale" },
  { id: "40", name: "Robot Lawn Mower" },
  { id: "41", name: "3D Printer" },
  { id: "42", name: "Drone" },
  { id: "43", name: "Electric Scooter" },
  { id: "44", name: "Electric Bike" },
  { id: "45", name: "Smart Glasses" },
  { id: "46", name: "Portable Projector" },
  { id: "47", name: "Noise Machine" },
  { id: "48", name: "Standing Desk" },
  { id: "49", name: "Monitor Stand" },
  { id: "50", name: "Cable Organizer" },
  { id: "51", name: "Surge Protector" },
  { id: "52", name: "Heat Gun" },
  { id: "53", name: "Laser Measure" },
  { id: "54", name: "Cordless Drill" },
  { id: "55", name: "Soldering Iron" },
  { id: "56", name: "Power Bank" },
  { id: "57", name: "Smart Plug" },
  { id: "58", name: "Solar Charger" },
  { id: "59", name: "Smart Curtain" },
  { id: "60", name: "Bluetooth Tracker" },
  { id: "61", name: "Smart Alarm Clock" },
  { id: "62", name: "Digital Piano" },
  { id: "63", name: "E-Reader" },
  { id: "64", name: "Streaming Device" },
  { id: "65", name: "Smart Lock" },
  { id: "66", name: "Smart Mirror" },
  { id: "67", name: "Home Assistant Device" },
  { id: "68", name: "Augmented Reality Glasses" },
  { id: "69", name: "Smart Bicycle Helmet" },
  { id: "70", name: "Smart Backpack" },
  { id: "71", name: "Voice Assistant Speaker" },
  { id: "72", name: "Personal Weather Station" },
  { id: "73", name: "Smart Refrigerator" },
  { id: "74", name: "Electric Grill" },
  { id: "75", name: "Compact Air Conditioner" },
  { id: "76", name: "Smart Water Bottle" },
  { id: "77", name: "Bluetooth Meat Thermometer" },
  { id: "78", name: "Smartphone Sanitizer" },
  { id: "79", name: "Sleep Tracker" },
  { id: "80", name: "Smart Plant Pot" },
  { id: "81", name: "WiFi Range Extender" },
  { id: "82", name: "Smart Baby Monitor" },
  { id: "83", name: "Digital Microscope" },
  { id: "84", name: "Portable Solar" },
];
